name: Deploy Frontend to S3

on:
  push:
    branches: [ "main" ] # change this to your default branch branch if it's "master"
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Build Frontend
        working-directory: ./frontend
        env:
          VITE_BACKEND_URL: http://51.20.87.168:4000
          # Update to action v4 to resolve Node 20 deprecation warning
        run: |
          npm install
          npm run build
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to S3
        working-directory: ./frontend
        # IMPORTANT: Replace YOUR_FRONTEND_BUCKET_NAME below
        run: aws s3 sync ./dist s3://my-pres-frontend --delete
